$(function(){
	$('#signout').click(function(){
		$.ajax({
			type:'post',
			url:'post_url/signout',
			success:function(){
				window.location.href='http://mdrifatul.info/ceramics/';
				return;
			}
		});
	});
});